....
======================================================================
FAIL: test_addusername_cases (__main__.test_addusername) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'guid': '', 'res': '10000', 'password': '123456', 'username': 'leecahk1u'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 251, in test_addusername_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #完善用户名模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10008 != 10000

======================================================================
FAIL: test_bindphone_cases (__main__.test_bindphone) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'guid': '', 'username': 'wuweihku', 'password': '123456', 'code_id': '', 'res': '10001'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 198, in test_bindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10001

======================================================================
FAIL: test_changepwdbycode_cases (__main__.test_changepwdbycode) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'username': 'wuweihku', 'password': '654321', 'code_id': '566e7427972c9', 'res': '10001'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 170, in test_changepwdbycode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #找回密码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10001

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'code_type': '1', 'guid': '', 'res': '10009', 'username': 'wuwei123123'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10009

----------------------------------------------------------------------
Ran 8 tests in 9.823s

FAILED (failures=4)
