..
======================================================================
FAIL: test_addusername_cases (__main__.test_addusername) (row={'guid': '', 'password': '', 'phone': '', 'username': 'qatesta', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10011', 'comments': 'guid为空且phone为空'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 251, in test_addusername_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #完善用户名模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10005 != 10011

======================================================================
FAIL: test_bindphone_cases (__main__.test_bindphone) (row={'guid': '', 'phone': '15692005742', 'password': '123456', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10014', 'code_id': '123456', 'comments': 'code_id错误'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 198, in test_bindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10014

======================================================================
FAIL: test_changepwdbycode_cases (__main__.test_changepwdbycode) (row={'phone': '15692005742', 'password': '123456', 'username': 'testblind', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10014', 'code_id': '123456', 'comments': 'code_id错误'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 170, in test_changepwdbycode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #找回密码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10014

======================================================================
FAIL: test_changepwdbycode_cases (__main__.test_changepwdbycode) (row={'phone': '18011963147', 'password': '654321', 'username': 'testblind', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'code_id': '999', 'comments': 'testblind修改密码'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 170, in test_changepwdbycode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #找回密码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10001

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10002', 'province': '', 'gender': '', 'income': '', 'comments': 'appid为空', 'appid': '', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10002

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10002', 'province': '', 'gender': '', 'income': '', 'comments': 'appid错误', 'appid': 'wrongappid', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10002

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'testnothere', 'res': '10009', 'province': '', 'gender': '', 'income': '', 'comments': 'username不存在', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10009

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '', 'gender': '', 'income': '', 'comments': 'nickname非法字符', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': 'nickname#$'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': 'post#$', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '', 'gender': '', 'income': '', 'comments': 'postcode非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '123', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '', 'gender': '', 'income': '', 'comments': 'postcode非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': 'address@#$', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '', 'gender': '', 'income': '', 'comments': 'address非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '0', 'gender': '', 'income': '', 'comments': 'province非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '99', 'gender': '', 'income': '', 'comments': 'province非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'postcode': '', 'address': '', 'job': '', 'username': 'qatest1', 'res': '10011', 'province': '$%', 'gender': '', 'income': '', 'comments': 'province非法', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'education': '', 'industry': '', 'nickname': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10011

======================================================================
FAIL: test_findbindphone_cases (__main__.test_findbindphone) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'username': 'qatest1', 'comments': 'appid正确且成功'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 104, in test_findbindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10001

======================================================================
FAIL: test_findbindphone_cases (__main__.test_findbindphone) (row={'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'username': 'qatest1', 'comments': 'username正确且成功'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 104, in test_findbindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10001

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '15692005742', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10012', 'code_type': '', 'comments': 'code_type为空'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '15692005742', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10012', 'code_type': '0', 'comments': 'code_type非法-0'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '15692005742', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10012', 'code_type': '3', 'comments': 'code_type非法-3'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10008 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '15692005742', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10012', 'code_type': '%', 'comments': 'code_type非法字符'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '13427680261', 'username': 'qatest6', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'code_type': '1', 'comments': 'code_type正确且成功'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10008 != 10001

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': 'thisisguid', 'phone': '15692005742', 'username': '', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'code_type': '1', 'comments': 'username为空使用guid成功'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10003 != 10001

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'guid': '', 'phone': '18011963147', 'username': 'testblind', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'res': '10001', 'code_type': '2', 'comments': 'testblind获取验证码用于修改密码'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10009 != 10001

----------------------------------------------------------------------
Ran 8 tests in 16.067s

FAILED (failures=23)
